services:
    php:
        build:
            context: ./php
        container_name: MosPromHr
        restart: unless-stopped
        volumes:
          - ./../:/var/www/html
          - sock:/sock
        user: root
        expose:
          - 9005
        extra_hosts:
          - "host.docker.internal:host-gateway"
        environment:
            APP_URL: ${APP_URL}
            DB_DATABASE: ${DB_DATABASE}
            DB_HOST: ${DB_HOST}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        networks:
            - backend
    db:
        image: postgres:latest
        container_name: MosPromHrDb
        environment:
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_DB: ${DB_DATABASE}
        volumes:
          - ./pgsql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
        networks:
            - backend
        ports:
          - "5432:5432"
    nginx:
        build:
            context: ./nginx
        container_name: MosPromHrNginx
        ports:
          - 81:80
        depends_on:
            - php
        restart: unless-stopped
        volumes:
            - ./../:/var/www/html/:delegated
            - sock:/sock
        networks:
            - backend
networks:
    backend:
        driver: bridge
volumes:
    sock:
